#!/bin/bash

pgrep dockerd &> /dev/null || echo "The Docker daemon is not running. Please install Docker and enable the Docker service." ; exit

docker run -ti -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/dri/card0 -v /run/user/$UID/pulse/native:/tmp/pulse -v /dev/shm:/dev/shm -v /etc/machine-id:/etc/machine-id -v /home/$USER/.steam/steam/steamapps/common/Robocraft:/home/robo/Robocraft askannz/robocraft
